### ISSUE TITLE
can't record mp3 second time

### ISSUE THREAD

**Issue by ortrails** [collab-project/videojs-record#265]
## Description
Using audio-only-mp3.html on Chrome browser the first time I am able to record, but the second time I am not able to record and I get a DOMException.

## Steps to reproduce
Record on audio-only-mp3.html 2 times using Chrome browser.
https://collab-project.github.io/videojs-record/examples/audio-only-mp3.html

### Expected
Expected to be able to re-record and have it work.

### Actual
Was not able to re-record because I got a DOMException.
[test.www.com-1532976536983.log](https://github.com/collab-project/videojs-record/files/2242493/test.www.com-1532976536983.log)
.

### Error output
If there are any errors at all, please include them here.
![capture](https://user-images.githubusercontent.com/6182481/43417267-c4b382c6-93f7-11e8-9e73-73d65cfc3c18.PNG)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.0.5
#### browsers
Google Chrome
#### OSes
Windows 10

**Comment by thijstriemstra** [comment]
this looks like a bug.

**Comment by thijstriemstra** [comment]
Fixed in 2.4.0

**Comment by ortrails** [comment]
I am still getting an error when I click the record button.
video.min.js:12 VIDEOJS: ERROR: DOMException: Failed to execute 'connect' on 'AudioNode': Cannot connect after the context has been closed.
    at LamejsEngine.start (http://localhost:53687/videojs-record/dist/plugins/videojs.record.lamejs.js:189:34)
    at Record.startRecording (http://localhost:53687/videojs-record/dist/videojs.record.js:2441:25)
    at Record.start (http://localhost:53687/videojs-record/dist/videojs.record.js:2414:30)
    at RecordToggle.handleClick (http://localhost:53687/videojs-record/dist/videojs.record.js:797:18)
    at HTMLButtonElement.r (http://localhost:53687/videojs-record/node_modules/video.js/dist/video.min.js:12:12778)
    at HTMLButtonElement.o.dispatcher.o.dispatcher (http://localhost:53687/videojs-record/node_modules/video.js/dist/video.min.js:12:10757)

**Comment by thijstriemstra** [comment]
@ortrails the online demo's have also been updated, can you reproduce it there as well?

**Comment by ortrails** [comment]
Yes it repros here -
https://collab-project.github.io/videojs-record/examples/audio-only-mp3.html

**Comment by thijstriemstra** [comment]
You're right, very poor testing on my side.

**Comment by ortrails** [comment]
The error happens at line 47 of lamejs-plugin.js.  It appears to be because this.audioSourceNode.Active = false.

**Comment by thijstriemstra** [comment]
@ortrails can you give PR #267 a try?

**Comment by ortrails** [comment]
@thijstriemstra works for me. recording first time works, recording 2nd and 3rd time works as well.
