### ISSUE TITLE
iOS Safari video 90deg rotation issue

### ISSUE THREAD

**Issue by harveymusni** [collab-project/videojs-record#741]
This issue happens only on iOS devices when recording in Safari.
The issue is that when the orientation is 0 (portrait mode), the recorded video frames are rotated 90 degrees anti-clockwise. If you rotate the device 90 degrees to the left and record in landscape mode, the video frames are recorded upside down but maintain the correct aspect ratio. 
If I save(upload) this by using Mux and play it, it's still rotated. It's happening even when I preview it before uploading.

I already checked [this issue](https://github.com/collab-project/videojs-record/issues/370) which is saying solved, but it's not solved actually.

### Expected
Video should be recorded as what I recorded, no need any rotation.

### Actual
In iOS safari, it's rotated 90deg anti-clockwise.

### Versions
videojs: 8.19.1
videojs-record: 4.5.1
Recordrtc 5.6.2
mux-player: 1.3.0

**Comment by johnpuddephatt** [comment]
Looks like a Safari bug. Introduced in 18.4, fixed but missed the 18.5 deadline a few weeks ago so hopefully it'll land soon.

https://bugs.webkit.org/show_bug.cgi?id=290223

**Comment by sanamumtaz** [comment]
I'm not using videojs-record, instead directly using MediaRecorder. I fixed the orientation issue by changing the mimetype from `video/webm` to `video/mp4`. The mimetype for the recorded video should be `mp4` because although `webm` is now "supported" but it's still a hit-or-miss.

**Comment by deepak786** [comment]
Seems that [iOS 18.6](https://support.apple.com/en-in/121161) is already released. Does it contain the fix?

**Comment by lagudafuad** [comment]
Still happening on iOS 26.6, and Android Chrome behaves the same way: the track reports the landscape sensor buffer while the browser draws the rotated portrait frame, and on iOS the rotation flag is no longer written to the file. Asking for width 1920 and height 1080 (not 1080 by 1920) gets Safari to rotate the picture, and when the reported size and the drawn frame still disagree, recording through a canvas of the drawn frame gives a correct file. Standalone code here: https://github.com/lagudafuadtosin/web-teleprompter/blob/master/src/lib/camera.ts
